name: FortiDevSec Scanner CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]


jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2
        - name: List files in the repository
          run: |
             echo "Listing files in the repository:"
             ls -R
        - name: fdevsec.yaml
          run: |
            if [ -f "fdevsec.yaml" ]; then
              echo "Printing contents of test.yaml:"
              cat fdevsec.yaml  # Use 'cat' to print the content of the file
            else
              echo "fdevsec.yaml file does not exist."
            fi
        - name: Print GitHub environment variable
          run: |
            echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
            echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
            echo "GITHUB_SHA: $GITHUB_SHA"
            echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        
        - name: SAST
          run: |
            env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
            docker run  --rm --env-file /tmp/env --add-host fortidevsec.forticloud.com:10.34.160.24 --mount type=bind,source=$(pwd),target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
